[package]
name = "shard"
version = "0.1.0"
authors = ["Julian Karrer"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
enum-map = "2.7.3"
halfbrown = "0.2.4"
pest = "2.7.5"
pest_derive = "2.7.5"