[package]
name = "shard"
version = "0.1.0"
authors = ["Julian Karrer"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deunicode = "1.4.1"
pest = "2.7.5"
pest_derive = "2.7.5"